export const projectData = [
  {
    id: 1,
    title: "Project 1",
    description: "This is the description for Project 1",
    image: "/images/project1.jpg",
    link: "https://project1.com",
    githubUrl: "https://github.com/project1",
  },
  {
    id: 2,
    title: "Project 2",
    description: "This is the description for Project 2",
    image: "/images/project2.jpg",
    link: "https://project2.com",
    githubUrl: "https://github.com/project2",
  },
  {
    id: 3,
    title: "Project 3",
    description: "This is the description for Project 3",
    image: "/images/project3.jpg",
    link: "https://project3.com",
    githubUrl: "https://github.com/project3",
  },
  {
    id: 4,
    title: "Project 4",
    description: "This is the description for Project 4",
    image: "/images/project4.jpg",
    link: "https://project4.com",
    githubUrl: "https://github.com/project4",
  },
  {
    id: 5,
    title: "Project 5",
    description: "This is the description for Project 5",
    image: "/images/project5.jpg",
    link: "https://project5.com",
    githubUrl: "https://github.com/project5",
  },
  {
    id: 6,
    title: "Project 6",
    description: "This is the description for Project 6",
    image: "/images/project6.jpg",
    link: "https://project6.com",
    githubUrl: "https://github.com/project6",
  },
];
