import Footer from "./_components/footer";
import Navbar from "./_components/navbar";
import Head from "next/head";
import CustomLayout from "./_components/customLayout";
import Image from "next/image";
import AnimatedText from "./_components/animated-text";
import Link from "next/link";
import { Button } from "./_components/ui/button";
import { FaExternalLinkAlt } from "react-icons/fa";
import HireMe from "./_components/hire-me";
import Programmer from "../public/programmer.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Artur Campos</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <main className="text-dark flex min-h-screen w-full flex-col items-center justify-center px-4 sm:max-w-[1000px] sm:px-8 lg:max-w-[1200px] lg:flex-row xl:max-w-[1500px] 2xl:max-w-[1800px]">
        <CustomLayout>
          <div className="flex w-full flex-col items-center justify-between lg:flex-row">
            <div className="h-full w-full sm:w-1/2 sm:max-w-[50%] lg:mr-4">
              <Image
                src="/developer2-bgrm.png"
                alt="Artur Campos"
                className="h-auto w-full rounded-full p-2 sm:p-4 lg:p-8"
                width={0}
                height={0}
                sizes="100vw"
              />
            </div>
            <div className="flex w-full flex-col items-center lg:ml-4 lg:w-1/2 lg:items-start">
              <AnimatedText
                text="Olá, eu sou o Artur! 👋        Transformando ideias em realidade com código e design"
                className="text-left text-xl sm:text-2xl lg:text-3xl xl:text-4xl"
              />
              <p className="my-4 text-xs sm:text-sm lg:text-base">
                Desenvolvedor de software com mais de 5 anos de experiência em
                desenvolvimento web, um dev fullstack apaixonado por inovação e
                novos desafios de tecnologia!. Com habilidades em HTML, CSS,
                JavaScript, React, Node.js, MongoDB, TypeScript e{" "}
                <strong>muito mais!</strong>
              </p>
              <div className="mt-2 flex flex-wrap items-center gap-4 self-center lg:self-start">
                <Button asChild>
                  <Link
                    href={"/curriculum.pdf"}
                    target="_blank"
                    download
                    className="text-xs font-semibold sm:text-sm lg:text-base"
                  >
                    Download Curriculum
                    <FaExternalLinkAlt className="mb-1 ml-1 w-4 sm:w-5 lg:w-6" />
                  </Link>
                </Button>
                <Button asChild variant={"outline"} className="border-black">
                  <Link
                    href="https://curriculum-sandy.vercel.app/"
                    target="_blank"
                    className="text-xs sm:text-sm lg:text-base"
                  >
                    Currículo Online
                  </Link>
                </Button>
              </div>
              <Button asChild variant={"ghost"} className="mt-2">
                <Link
                  href={"mailto:arturcamposba99@gmail.com"}
                  target="_blank"
                  className="text-xs font-medium underline sm:text-sm lg:text-base"
                >
                  Entre em contato comigo
                </Link>
              </Button>
            </div>
          </div>
        </CustomLayout>
      </main>
      <HireMe />
      <div className="absolute bottom-8 right-8 w-12 pt-36 sm:w-16 lg:w-20">
        <Image
          src={Programmer}
          alt="developer"
          className="h-auto w-full rounded-full"
          width={0}
          height={0}
          sizes="(max-width: 768px) 100vw, 33vw"
        />
      </div>
      <Footer />
    </>
  );
}
