// import Hero from "./_components/hero";
// import About from "./_components/about";
import Footer from "./_components/footer";
import Navbar from "./_components/navbar";
// import Skills from "./_components/skills";
// import Projects from "./_components/projects";
// import ContactForm from "./_components/contact";
import Head from "next/head";
import CustomLayout from "./_components/customLayout";
import Image from "next/image";
import AnimatedText from "./_components/animated-text";

export default function Home() {
  return (
    <>
      <Head>
        <title>Artur Campos</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <main className="text-dark flex min-h-screen w-full items-center">
        <CustomLayout>
          <div className="flex w-full items-center justify-between">
            <div className="w-1/2">
              <Image
                src="/developer2.jpeg"
                alt="Artur Campos"
                className="h-auto w-[70%] rounded-full"
                width={0}
                height={0}
                sizes="100vw"
              />
            </div>
            <div className="flex w-1/2 flex-col items-center self-center ">
              <AnimatedText
                text={
                  "Olá, eu sou o Artur! Transformando ideias em realidade com código e design"
                }
                className="!text-left !text-5xl"
              />
              <p className=" text-lg">
                Desenvolvedor de software com mais de 5 anos de experiência em
                desenvolvimento web, um dev fullstack apaixonado por inovação e
                novos desafios de tecnologia!. Com habilidades em HTML, CSS,
                JavaScript, React, Node.js, MongoDB, TypeScript e{" "}
                <strong>muito mais!</strong>
              </p>
            </div>
          </div>
        </CustomLayout>
        {/* <Hero />
          <About />
          <Skills />
          <Projects />
          <ContactForm /> */}
      </main>
      <Footer />
    </>
  );
}
